spring.application.name=estudiantes

# Conexión MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/estudiantes
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Evitar que el esquema se cree nuevamente (duplicado)
spring.jpa.hibernate.ddl-auto=none

# Mostrar las queries que se van a ejecutar
spring.jpa.show-sql=true

# Desactivar tomcat (para webapps)
spring.main.web-application-type=none

